import { GameBoyAdvance } from "./gba";
export declare class GameBoyAdvanceKeypad {
    core: GameBoyAdvance;
    KEYCODE_LEFT: number;
    KEYCODE_UP: number;
    KEYCODE_RIGHT: number;
    KEYCODE_DOWN: number;
    KEYCODE_START: number;
    KEYCODE_SELECT: number;
    KEYCODE_A: number;
    KEYCODE_B: number;
    KEYCODE_L: number;
    KEYCODE_R: number;
    GAMEPAD_LEFT: number;
    GAMEPAD_UP: number;
    GAMEPAD_RIGHT: number;
    GAMEPAD_DOWN: number;
    GAMEPAD_START: number;
    GAMEPAD_SELECT: number;
    GAMEPAD_A: number;
    GAMEPAD_B: number;
    GAMEPAD_L: number;
    GAMEPAD_R: number;
    GAMEPAD_THRESHOLD: number;
    A: number;
    B: number;
    SELECT: number;
    START: number;
    RIGHT: number;
    LEFT: number;
    UP: number;
    DOWN: number;
    R: number;
    L: number;
    PRESS_TIME: number;
    currentDown: number;
    eatInput: boolean;
    gamepads: any[];
    remappingKeyId: string;
    constructor();
    press(key: any, time?: any): void;
    keyboardHandler(e: any): void;
    gamepadHandler(gamepad: any): void;
    gamepadConnectHandler(gamepad: any): void;
    gamepadDisconnectHandler(gamepad: any): void;
    pollGamepads(): void;
    registerHandlers(): void;
    initKeycodeRemap(keyId: any): void;
    remapKeycode(keyId: any, keycode: any): void;
}
